spring:
  application:
    name: provider-service
  jackson.serialization.indent_output: true
  zipkin:
    enabled: true
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率, 默认0.1
      percentage: 0.2
server:
  port: 20001
endpoints:
  sensitive: false
common:
  test-a: test-a
  test-b: test-b
  ops:
    accessLog: db
    errorLog: db
eureka:
  client:
    healthcheck:
      enabled: true
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 30




