spring:
  application:
    name: feign-service
  zipkin:
    enabled: true
    base-url: http://localhost:9411
  sleuth:
    sampler:
      #采样率, 默认0.1
      percentage: 1.0
server:
  port: 40001
endpoints:
  sensitive: false

eureka:
  client:
    enabled: true
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
    healthcheck:
      enabled: true
#  instance:
#    prefer-ip-address: true
#    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
#feign.hystrix.enabled: false
#feign.retry.enabled: false
hystrix:
 command:
   default:
     execution:
       isolation:
         thread:
           timeoutInMilliseconds: "60000"
