spring:
  application:
    name: eureka-server
server:
  port: 10001
endpoints:
  sensitive: false
eureka:
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 4000
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      defaultZone: http://localhost:10001/eureka/
  instance:
    hostname: localhost