spring:
  application:
    name: ribbon-service
server:
  port: 30001
endpoints:
  sensitive: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:10001/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000